#!/bin/sh
# Copyright (C) 2016 MOHAMED Kallel <mohamed.kallel@yahoo.fr>

#common_execute_method_param "$parameter" "$permission" "$get_cmd" "$set_cmd" "xsd:$type" "$forcedinform"
#  $forcedinform should be set to 1 if the parameter is included in the inform message otherwise empty
#  Default of $type = string

#############################
#   Entry point functions   #
#############################

prefix_list="$prefix_list $DMROOT.WiFi."
entry_execute_method_list="$entry_execute_method_list entry_execute_method_root_WiFi"
mcs_tmp_file="/tmp/.easycwmp_mcs"
pw_list_dir="/usr/share/easycwmp"

entry_execute_method_root_WiFi() {
	case "$1" in ""|"$DMROOT."|"$DMROOT.WiFi."*)
		common_execute_method_obj "$DMROOT.WiFi." "0"
		common_execute_method_param "$DMROOT.WiFi.RadioNumberOfEntries" "0" "wifi_get_RadioNumberOfEntries $1" "" "xsd:unsignedInt" "1"
		common_execute_method_param "$DMROOT.WiFi.SSIDNumberOfEntries" "0" "wifi_get_SSIDNumberOfEntries $1" "" "xsd:unsignedInt" "1"
		common_execute_method_param "$DMROOT.WiFi.AccessPointNumberOfEntries" "0" "wifi_get_AccessPointNumberOfEntries $1" "" "xsd:unsignedInt" "1"
		common_execute_method_param "$DMROOT.WiFi.EndPointNumberOfEntries" "0" "wifi_get_EndPointNumberOfEntries $1" "" "xsd:unsignedInt" "1"
		common_execute_method_param "$DMROOT.WiFi.Reset" "1" "echo" "wifi_reset $1" "xsd:boolean" "1"
		common_execute_method_obj "$DMROOT.WiFi.Radio." "0" "" "" "wifi_radio_browse_instances $1"
		common_execute_method_obj "$DMROOT.WiFi.SSID." "1" "add_wifi_ssid" "" "wifi_ssid_browse_instances $1"
		common_execute_method_obj "$DMROOT.WiFi.AccessPoint." "1" "add_wifi_ap" "" "wifi_ap_browse_instances $1"
		return 0
		;;
	esac
	return $E_INVALID_PARAMETER_NAME;
}

sub_entry_WiFi_Radio() {
	local j="$2"
	local radio="$3"
	case_param "$1" belongto "$DMROOT.WiFi.Radio.$j." && {
		common_execute_method_obj "$DMROOT.WiFi.Radio.$j." "0"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.Enable" "1" "wifi_radio_get_Enable $radio" "wifi_radio_set_Enable $radio" "xsd:boolean" "1"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.Status" "0" "wifi_radio_get_Status $radio" "" "xsd:string" "1"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.Name" "0" "wifi_radio_get_Name $radio" "" "xsd:string" "1"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.MaxBitRate" "0" "wifi_radio_get_MaxBitRate $radio" "" "xsd:unsignedInt" "1"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.SupportedFrequencyBands" "0" "wifi_radio_get_SupportedFrequencyBands $radio" "" "xsd:string" "1"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.OperatingFrequencyBand" "0" "wifi_radio_get_OperatingFrequencyBand $radio" "" "xsd:string" "1"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.SupportedStandards" "0" "wifi_radio_get_SupportedStandards $radio" "" "xsd:string" "1"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.OperatingStandards" "1" "wifi_radio_get_OperatingStandards $radio" "wifi_radio_set_OperatingStandards $radio" "xsd:string" "1"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.ChannelsInUse" "0" "wifi_radio_get_ChannelsInUse $radio" 
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.Channel" "1" "wifi_radio_get_Channel $radio" "wifi_radio_set_Channel $radio" "xsd:unsignedInt"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.AutoChannelSupported" "0" "echo 1" "" "xsd:boolean"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.AutoChannelEnable" "1" "wifi_radio_get_AutoChannelEnable $radio" "wifi_radio_set_AutoChannelEnable $radio" "xsd:boolean"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.SupportedOperatingChannelBandwidths" "0" "wifi_radio_get_SupportedOperatingChannelBandwidths $radio" "" "xsd:string" "1"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.OperatingChannelBandwidth" "1" "wifi_radio_get_OperatingChannelBandwidth $radio" "wifi_radio_set_OperatingChannelBandwidth $radio" "xsd:string" "1"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.GuardInterval" "1" "wifi_radio_get_GuardInterval $radio" "wifi_radio_set_GuardInterval $radio" "xsd:string" "1"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.MCS" "1" "wifi_radio_get_MCS $radio" "wifi_radio_set_MCS $radio" "xsd:int[-1:15, 16:31]" "1"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.TransmitPowerSupported" "0" "wifi_radio_get_TransmitPowerSupported $radio" "" "xsd:string" "1"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.TransmitPower" "1" "wifi_radio_get_TransmitPower $radio" "wifi_radio_set_TransmitPower $radio" "xsd:int[-1:100]" "1"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.RetryLimit" "1" "wifi_radio_get_RetryLimit $radio" "wifi_radio_set_RetryLimit $radio" "xsd:unsignedInt[0:7]" "1"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.FragmentationThreshold" "1" "wifi_radio_get_FragmentationThreshold $radio" "wifi_radio_set_FragmentationThreshold $radio" "xsd:unsignedInt" "1"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.RTSThreshold" "1" "wifi_radio_get_RTSThreshold $radio" "wifi_radio_set_RTSThreshold $radio" "xsd:unsignedInt" "1"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.LongRetryLimit" "1" "wifi_radio_get_LongRetryLimit $radio" "wifi_radio_set_LongRetryLimit $radio" "xsd:unsignedInt" "1"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.BeaconPeriod" "1" "wifi_radio_get_BeaconPeriod $radio" "wifi_radio_set_BeaconPeriod $radio" "xsd:unsignedInt" "1"
		common_execute_method_param  "$DMROOT.WiFi.Radio.$j.PreambleType" "1" "wifi_radio_get_PreambleType $radio" "wifi_radio_set_PreambleType $radio" "xsd:string" "1"
		return 0
	}
	return $E_INVALID_PARAMETER_NAME;		
}

sub_entry_WiFi_SSID() {
	local j="$2"
	local iface="$3"
	case_param "$1" belongto "$DMROOT.WiFi.SSID.$j." && {
		common_execute_method_obj "$DMROOT.WiFi.SSID.$j." "1" "" "del_wifi_ssid $iface"
		common_execute_method_param  "$DMROOT.WiFi.SSID.$j.Enable" "1" "wifi_ssid_get_Enable $iface" "wifi_ssid_set_Enable $iface" "xsd:boolean"
		common_execute_method_param  "$DMROOT.WiFi.SSID.$j.Status" "0" "wifi_ssid_get_Status $iface"
		common_execute_method_param  "$DMROOT.WiFi.SSID.$j.Name" "0" "wifi_ssid_get_Name $iface"
		common_execute_method_param  "$DMROOT.WiFi.SSID.$j.LowerLayers" "1" "wifi_ssid_get_LowerLayers $iface" "wifi_ssid_set_LowerLayers $iface"
		common_execute_method_param  "$DMROOT.WiFi.SSID.$j.SSID" "1" "wifi_ssid_get_SSID $iface" "wifi_ssid_set_SSID $iface"
		common_execute_method_param  "$DMROOT.WiFi.SSID.$j.X_IPInterface" "1" "wifi_ssid_get_X_IPInterface $iface" "wifi_ssid_set_X_IPInterface $iface"
		return 0
	}
	return $E_INVALID_PARAMETER_NAME;		
}

sub_entry_WiFi_AccessPoint() {
	local j="$2"
	local iface="$3"
	case_param "$1" belongto "$DMROOT.WiFi.AccessPoint.$j." && {
		common_execute_method_obj "$DMROOT.WiFi.AccessPoint.$j." "1" "" "del_wifi_ap $iface"
		common_execute_method_param  "$DMROOT.WiFi.AccessPoint.$j.Enable" "1" "wifi_ap_get_Enable $iface" "wifi_ap_set_Enable $iface" "xsd:boolean"
		common_execute_method_param  "$DMROOT.WiFi.AccessPoint.$j.Status" "0" "wifi_ap_get_Status $iface"
		common_execute_method_param  "$DMROOT.WiFi.AccessPoint.$j.SSIDReference" "0" "echo $DMROOT.WiFi.SSID.$j."
		common_execute_method_obj "$DMROOT.WiFi.AccessPoint.$j.Security." "0"
		common_execute_method_param  "$DMROOT.WiFi.AccessPoint.$j.Security.ModesSupported" "0" "wifi_ap_get_ModesSupported $iface"
		common_execute_method_param  "$DMROOT.WiFi.AccessPoint.$j.Security.ModeEnabled" "1" "wifi_ap_get_ModeEnabled $iface" "wifi_ap_set_ModeEnabled $iface"
		common_execute_method_param  "$DMROOT.WiFi.AccessPoint.$j.Security.WEPKey" "1" "wifi_get_secret" "wifi_ap_set_WEPKey $iface" "xsd:hexBinary­"
		common_execute_method_param  "$DMROOT.WiFi.AccessPoint.$j.Security.PreSharedKey" "1" "wifi_get_secret" "wifi_ap_set_PreSharedKey $iface" "xsd:hexBinary­"
		common_execute_method_param  "$DMROOT.WiFi.AccessPoint.$j.Security.KeyPassphrase" "1" "wifi_get_secret" "wifi_ap_set_KeyPassphrase $iface"
		return 0
	}
	return $E_INVALID_PARAMETER_NAME;		
}

wifi_reset() {
	[ "$2" = "1" -o "$2" = "true" ] && wifi
	echo $?
}

wifi_get_EndPointNumberOfEntries() {
	echo `$UCI_SHOW wireless | grep "mode=\'sta\'" | wc -l`
}

wifi_get_RadioNumberOfEntries() {
	echo `$UCI_SHOW wireless | grep "=wifi-device" | wc -l`
}

wifi_get_AccessPointNumberOfEntries() {
	echo `$UCI_SHOW wireless | grep "mode=\'ap\'" | wc -l`
}

wifi_get_SSIDNumberOfEntries() {
	echo `$UCI_SHOW wireless | grep "=wifi-iface" | wc -l`
}

wifi_radio_get_max_instance() {
	local max=`$UCI_SHOW wireless | grep "wifi_radio_instance" | cut -d'=' -f2 | sed 's/[^0-9]*//g' | sort -nru | head -1`
	[ -z "$max" ] && echo 0 || echo ${max:-0}
}

wifi_ssid_get_max_instance() {
	local max=`$UCI_SHOW wireless | grep "wifi_ssid_instance" | cut -d'=' -f2 | sed 's/[^0-9]*//g' | sort -nru | head -1`
	[ -z "$max" ] && echo 0 || echo ${max:-0}
}

wifi_ap_get_max_instance() {
	local max=`$UCI_SHOW wireless | grep "wifi_ap_instance" | cut -d'=' -f2 | sed 's/[^0-9]*//g' | sort -nru | head -1`
	[ -z "$max" ] && echo 0 || echo ${max:-0}
}

wifi_radio_update_instance() {
	local radio="$1"
	local instance=`$UCI_GET $radio.wifi_radio_instance`
	if [ -z "$instance" ]; then
		instance=`wifi_radio_get_max_instance`
		$UCI_SET $radio.wifi_radio_instance=$((++instance))
		$UCI_COMMIT
	fi
	echo $instance
}

wifi_ssid_update_instance() {
	local iface="$1"
	local instance=`$UCI_GET $iface.wifi_ssid_instance`
	if [ -z "$instance" ]; then
		instance=`wifi_ssid_get_max_instance`
		$UCI_SET $iface.wifi_ssid_instance=$((++instance))
		$UCI_COMMIT
	fi
	echo $instance
}

wifi_ap_update_instance() {
	local iface="$1"
	local instance=`$UCI_GET $iface.wifi_ap_instance`
	if [ -z "$instance" ]; then
		instance=`wifi_ap_get_max_instance`
		$UCI_SET $iface.wifi_ap_instance=$((++instance))
		$UCI_COMMIT
	fi
	echo $instance
}

wifi_radio_browse_instances() {
	local radio radios=`$UCI_SHOW wireless | grep "wireless\..*=wifi-device" | cut -d "=" -f 1`
	for radio in $radios; do
		local j=`wifi_radio_update_instance $radio`
		sub_entry_WiFi_Radio  "$1" "$j" "$radio"
	done
}

wifi_ssid_browse_instances() {
	local iface ifaces=`$UCI_SHOW wireless | grep "wireless\..*=wifi-iface" | cut -d "=" -f 1`
	for iface in $ifaces; do
		local j=`wifi_ssid_update_instance $iface`
		sub_entry_WiFi_SSID  "$1" "$j" "$iface"
	done
}

wifi_ap_browse_instances() {
	local iface ifaces=`$UCI_SHOW wireless | grep ".mode=\'ap\'" | awk 'BEGIN{FS=".";} {print $1"."$2}'`
	for iface in $ifaces; do
		local j=`wifi_ap_update_instance $iface`
		sub_entry_WiFi_AccessPoint  "$1" "$j" "$iface"
	done
}

#need to modify
add_wifi_ssid() {
	local instance=`wifi_ssid_get_max_instance`
	local section=`$UCI_ADD  wireless wifi-iface`
	$UCI_SET wireless.$section.wifi_ssid_instance=$((++instance))
	$UCI_COMMIT
	echo $instance
}

#todo
add_wifi_ap() {
	return 0
}

#need to modify
del_wifi_ssid() {
	local iface="$1"
	$UCI_DELETE $iface
	$UCI_COMMIT
	return 0
}

#todo
del_wifi_ap() {
	return 0
}

wifi_radio_get_Enable() {
	local val=`$UCI_GET $1.disabled`
	[ "$val" = "1" ] && echo "0" || echo "1"
}

wifi_radio_set_Enable() {
	local ret
	common_set_bool "$1.disabled" "$2" "" "1"
	ret=$?
	return $ret
}

wifi_radio_get_Status() {
	local device=${1#*.}
	local res up

	res=`ubus call network.wireless status`
	if [ "$res" != "" ]; then
		json_init
		json_load "$res" >&2
		json_select "$device" >&2
		json_get_var up up >&2
	fi
	[ "$up" = "1" ] && echo Up || echo Down
}

wifi_radio_get_Name() {
	echo ${1#*.}
}

wifi_radio_get_SupportedFrequencyBands() {
	local phy="phy${1#*radio}"
	local freq=`iw phy $phy info | grep  "MHz.*dBm" | head -1 | awk '{print $2}'`
	[ "${freq#24}" = "$freq" ] && echo "5GHz" || echo "2.4GHz"
}

wifi_radio_get_OperatingFrequencyBand() {
	echo `wifi_radio_get_SupportedFrequencyBands $1`
}

wifi_radio_get_ChannelsInUse() {
	local freq="`iw phy phy0 info | grep  MHz.*dBm | awk -F'[][]' '{print $2}' |  tr '\n' ','`"
	echo ${freq%,}
}

wifi_radio_get_Channel() {
	local channel phy freq

	channel=`$UCI_GET $1.channel`
	[ "$channel" != "" -a "$channel" != "auto" ] && { echo $channel; return; }

	phy="phy${1#*radio}"
	freq=`iw phy $phy info | grep  "MHz.*dBm" | head -1 | awk '{print $2}'`
	if [ "${freq#24}" != "$freq" ]; then 
		channel=`iw dev | grep "channel.*(24.*MHz)" | head -1 | awk '{print $2}'`
	else
		channel=`iw dev | grep "channel" | grep -v "channel.*(24.*MHz)" | head -1 | awk '{print $2}'`		
	fi
	echo $channel
}

wifi_radio_set_Channel() {
	$UCI_SET $1.channel=$2
}

wifi_radio_get_AutoChannelEnable() {
	local en=`$UCI_GET $1.channel`
	[ "$en" = "" -o "$en" = "auto" ] && echo 1 || echo 0
}

wifi_radio_set_AutoChannelEnable() {
	local val=`echo "$2" | tr '[A-Z]' '[a-z]'`
	if [ "$val" = "1" -o "$val" = "true" ]; then
		$UCI_SET $1.channel=auto
	else
		local channel=`wifi_radio_get_Channel $1`
		$UCI_SET $1.channel=$channel
	fi	
}

#need to modify to support 802.11ac
wifi_radio_get_OperatingStandards() {
	local val=`$UCI_GET $1.hwmode`
	local htmode=`$UCI_GET $1.htmode`
	[ ! -z "$htmode" ] && val="n"
	echo ${val#11}
}
######

wifi_radio_set_OperatingStandards() {
	$UCI_SET $1.hwmode=11$2
}

wifi_ssid_get_Enable() {
	local val=`$UCI_GET $1.disabled`
	[ "$val" = "1" ] && echo "0" || echo "1"
}

wifi_ssid_set_Enable() {
	local ret
	common_set_bool "$1.disabled" "$2" "" "1"
	ret=$?
	return $ret
}

wifi_ssid_get_Status() {
	local name=`wifi_ssid_get_Name $1`
	[ "$name" != "" ] && echo Up || echo Down
}

wifi_ssid_get_Name() {
	local iface=$1
	local res ifname section device e i=0

	device=`$UCI_GET $1.device`
	[ "$device" = "" ] && return 0
	res=`ubus call network.wireless status`
	[ "$res" = "" ] && return 0
	json_init
	json_load "$res"
	json_select "$device"
	json_select "interfaces"
	while [ 1 ]; do
		let i++
		json_select "$i"  >&2
		e=$?
		[ "$e" != 0 ] && break
		json_get_var section section >&2
		[ "$section" != "${iface#*.}" ] && { json_select ".." >&2; continue; }
		json_get_var ifname ifname >&2
		echo $ifname
		break;
	done
}

wifi_ssid_get_LowerLayers() {
	local device=`$UCI_GET $1.device`
	local instance=`$UCI_GET wireless.$device.wifi_radio_instance`
	[ "$instance" != "" ] && echo "$DMROOT.WiFi.Radio.$instance."
}

wifi_ssid_set_LowerLayers() {
	local tmp=${2#$DMROOT.WiFi.Radio.}
	[ "$tmp" = "$2" ] && return
	local instance=${tmp%.}
	[ "$tmp" = "$instance" ] && return
	local device=`$UCI_SHOW wireless | grep "wifi_radio_instance=$instance" | cut -d'.' -f2`
	$UCI_SET $1.device=$device
}

wifi_ssid_get_SSID() {
	local ssid=`$UCI_GET $1.ssid`
	echo $ssid
}

wifi_ssid_set_SSID() {
	$UCI_SET $1.ssid=$2
}

wifi_ssid_get_X_IPInterface() {
	local network=`$UCI_GET $1.network`
	local instance=`$UCI_GET network.$network.ip_int_instance`
	[ "$instance" != "" ] && echo "$DMROOT.IP.Interface.$instance."
}

wifi_ssid_set_X_IPInterface() {
	local tmp=${2#$DMROOT.IP.Interface.}
	[ "$tmp" = "$2" ] && return
	local instance=${tmp%.}
	[ "$tmp" = "$instance" ] && return
	local network=`$UCI_SHOW network | grep "ip_int_instance=$instance" | cut -d'.' -f2`
	$UCI_SET $1.network=$network
}

wifi_ap_get_Enable() {
	local val=`$UCI_GET $1.disabled`
	[ "$val" = "1" ] && echo "0" || echo "1"
}

wifi_ap_set_Enable() {
	local ret
	common_set_bool "$1.disabled" "$2" "" "1"
	ret=$?
	return $ret
}

wifi_ap_get_Status() {
	local name=`wifi_ssid_get_Name $1`
	[ "$name" != "" ] && echo Enabled || echo Disabled
}

wifi_ap_get_ModesSupported() {
	echo "None,WEP-64,WEP-128,WPA-Personal,WPA2-Personal,WPA-WPA2-Personal,WPA-Enterprise,WPA2-Enterprise,WPA-WPA2-Enterprise"
}

wifi_ap_get_ModeEnabled() {
	local key
	local encryption=`$UCI_GET $1.encryption`
	
	case "$encryption" in
		"psk2"*)
			echo "WPA2-Personal"
			;;
		"psk-mixed"*)
			echo "WPA-WPA2-Personal"
			;;
		"psk"*)
			echo "WPA-Personal"
			;;
		"wpa2"*)
			echo "WPA2-Enterprise"
			;;
		"wpa-mixed"*)
			echo "WPA-WPA2-Enterprise"
			;;
		"wpa"*)
			echo "WPA-Enterprise"
			;;
		"wep"*)
			key=`$UCI_GET $1.key`
			[ "$key" = "1" -o "$key" = "2" -o "$key" = "3" -o "$key" = "4" ] && key=`$UCI_GET $1.key$key`
			[ ${#key} = "26" ] && echo "WEP-128" || echo "WEP-64"
			;;
		*)
			echo "None"
			;;
	esac
}

wifi_ap_set_ModeEnabled() {
	local key
	local encryption=`wifi_ap_get_ModeEnabled $1`
	[ "$encryption" = "$2" ] && return 0
	
	case "$2" in
		"WPA2-Personal")
			$UCI_SET $1.encryption="psk2"
			;;
		"WPA-WPA2-Personal")
			$UCI_SET $1.encryption="psk-mixed"
			;;
		"WPA-Personal")
			$UCI_SET $1.encryption="psk"
			;;
		"WPA2-Enterprise")
			$UCI_SET $1.encryption="wpa2"
			;;
		"WPA-WPA2-Enterprise")
			$UCI_SET $1.encryption="wpa-mixed"
			;;
		"WPA-Enterprise")
			$UCI_SET $1.encryption="wpa"
			;;
		"WEP-64")
			$UCI_SET $1.encryption=wep
			$UCI_SET $1.key=1
			$UCI_SET $1.key1="0123456789012"
			;;
		"WEP-128")
			$UCI_SET $1.encryption=wep
			$UCI_SET $1.key=1
			$UCI_SET $1.key1="01234567890123456789012345"
			;;
		"None")
			$UCI_SET $1.encryption=
			$UCI_SET $1.key=
			;;
	esac
	return 0
}

wifi_get_secret() {
	return 0
}

wifi_ap_set_WEPKey() {
	$UCI_SET $1.key=1
	$UCI_SET $1.key1=$2
	return 0
}

wifi_ap_set_PreSharedKey() {
	$UCI_SET $1.key=$2
	return 0
}

wifi_ap_set_KeyPassphrase() {
	$UCI_SET $1.key=$2
	return 0
}

wifi_radio_get_MaxBitRate(){
	local phy=phy${1#*radio}
	local mcs=`iw $phy info | grep "HT TX/RX MCS rate indexes supported" | cut -d'-' -f2 | cut -d',' -f1`
	local std=`wifi_radio_get_OperatingStandards $1`
	if [ "$std" = "n" ]; then
		case $mcs in
			0) echo 15;;
			1|8) echo 30;;
			2|16) echo 45;;
			3|9|24) echo 60;;
			4|10|17) echo 90;;
			5|11|25) echo 120;;
			6|18) echo 135;;
			7) echo 150;;
			12|19|26) echo 180;;
			13|27) echo 240;;
			14|20) echo 270;;
			15) echo 300;;
			21|28) echo 360;;
			22) echo 405;;
			23) echo 450;;
			29) echo 480;;
			30) echo 540;;
			31) echo 600;;
		esac
	elif [ "$std" = "ac" ]; then
		case $mcs in
			0) echo 65;;
			1) echo 130;;
			2) echo 195;;
			3) echo 260;;
			4) echo 390;;
			5) echo 520;;
			6) echo 585;;
			7) echo 650;;
			8) echo 780;;
			9) echo 866.7;;
		esac
	else
		echo 54
	fi

}

#need to modify to support 802.11ac
wifi_radio_get_SupportedStandards() {
	local band=`wifi_radio_get_OperatingFrequencyBand $1`
	local stds=""
	local phy=phy${1#*radio}
	if [ "$band" = "5GHz" ]; then
		stds="a"
	else
		stds="b,g"	
	fi
	local tmp=`iw $phy info | grep "RX HT20 SGI"`
	[ ! -z "$tmp" ] && stds=$stds,"n"
	echo $stds
}

wifi_radio_get_SupportedOperatingChannelBandwidths() {
	local stds=`wifi_radio_get_SupportedStandards $1`
	local n=`echo $stds | grep "n"`
	local ac=`echo $stds | grep "ac"`
	local bw="20MHz"
	[ ! -z "$n" ] && bw=$bw,"40MHz"
	[ ! -z "$ac" ] && bw=$bw,"80MHz,160MHz"
	echo $bw
}

wifi_radio_get_OperatingChannelBandwidth() {
	local bw=`$UCI_GET $1.htmode`
	bw=${bw#HT}
	bw=${bw#V}
	bw=${bw%-}
	bw=${bw%+}
	echo $bw"MHz"
}

wifi_radio_get_GuardInterval() {
	local std=`wifi_radio_get_OperatingStandards $1`
	local bw=`wifi_radio_get_OperatingChannelBandwidth $1`
	bw=${bw%MHz}
	local shortgi=`$UCI_GET $1.short_gi_$bw`
	if [ "$std" = "n" -o "$std" = "ac" ]; then
		[ "$shortgi" = "0" ] && echo "800ns" || echo "400ns"
	fi
}

wifi_radio_get_MCS() {
	local mcs=`cat $mcs_tmp_file`
	[ -z "$mcs" ] && echo -1 || echo $mcs
}

wifi_radio_get_TransmitPowerSupported() {
	local phy=phy${1#*radio}
	local pwfile=$pw_list_dir/power_$phy
	rm -rf $pwfile
	#dBm list
	local dbmlist=`iwinfo $phy txpowerlist | tr '*' ' ' | awk '!_[$4]++' | awk '{print $1}'`
	local max=`echo "$dbmlist" | tail -1`
	IFS="
"
	local ppwlist=""
	local pre=""
	for pw in $dbmlist
	do
		local ppw=`expr $pw \* 100 / $max`
		#avoid duplication
		if [ ! "$ppw" = "$pre" ]; then
			pre=$ppw
			ppwlist=$ppwlist,$ppw
			#echo "$ppw% $pw" >> $pwfile
		fi
	done
	ppwlist=${ppwlist#,}
	unset IFS
	echo $ppwlist
}

wifi_radio_get_TransmitPower() {
	local pw=`$UCI_GET $1.txpower`
	if [ -z "$pw" ]; then
		echo -1
		return 0
	fi
	local phy=phy${1#*radio}
	local max=`iwinfo $phy txpowerlist | tr '*' ' ' | awk '!_[$4]++' | awk '{print $1}' | tail -1`
	echo `expr $pw \* 100 / $max`
}

wifi_radio_set_TransmitPower() {
	#ceil($tmp)
	#echo "$tmp" | awk '{printf("%d\n",$0+=$0<0?0:0.9)}'
	return 0
}

wifi_radio_get_RetryLimit() {
	local phy=phy${1#*radio}
	echo `iw $phy info | awk 'BEGIN{FS=": ";} /Retry short limit/ {print $2}'`
}

wifi_radio_get_FragmentationThreshold() {
	local phy=phy${1#*radio}
	local frag=`iw $phy info | awk 'BEGIN{FS=": ";} /Fragmentation threshold/ {print $2}'`
	#2346~off
	[ -z "$frag" ] && echo 2346 || echo $frag
}

wifi_radio_get_RTSThreshold() {
	local phy=phy${1#*radio}
	local rts=`iw $phy info | awk 'BEGIN{FS=": ";} /RTS threshold/ {print $2}'`
	#2347 ~ off
	[ -z "$rts" ] && echo 2347 || echo $rts
}

wifi_radio_get_LongRetryLimit() {
	local phy=phy${1#*radio}
	echo `iw $phy info | awk 'BEGIN{FS=": ";} /Retry long limit/ {print $2}'`
}

#need to check with non-MAC80211 driver
wifi_radio_get_BeaconPeriod() {
	local bp=`$UCI_GET $1.beacon_int`
	[ -z "$bp" ] && echo 100 || echo $bp
}

wifi_radio_get_PreambleType() {
	echo "todo"
}
